# Generated by Django 2.2.3 on 2019-09-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_file_q',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_file_q',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_file',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='practise',
            name='parctise_file',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_file_q',
            field=models.URLField(max_length=2000),
        ),
    ]
